-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep class org.json.** { *; }
-keep interface org.json.** { *; }
-keep class com.example.local_llm.tool.** { *; }
-keep class com.example.local_llm.agent.** { *; }
-keep class com.example.local_llm.backend.** { *; }
-dontwarn okhttp3.**
-dontwarn org.json.**
